### PR TITLE
Update Ultrawide fix to version 1.04

### PR DESCRIPTION
**Pull request by joao-pedro-braz**
Hello All,

This Feature updates the Ultrawide fix so it works with the 1.04 version of Elden Ring, released yesterday (20th of April 2022).

Evidence of the game running in a 21:9 resolution with the patch 1.04 applied:
image

Patch version (bottom right corner)
image

Best Regards,
João Pedro Braz

### CODE REVIEW

**Comment by gurrgur** [comment]
Thanks for this! I'd prefer to use a pattern with wildcards to make it more robust w.r.t. possible future game updates. Though it's better to have a working patch than a non-existent perfect one ;)

Unfortunately update 1.04 has made the game crash at launch for me so I cannot test this currently.. But the path looks fine overall so I'll merge :)

**Comment by joao-pedro-braz** [comment]
Hello!

Yeah, that's probably a good idea, I'll work on it.
Currently there's 4 patches with "." instead of "*", I'll change them all in another PR, as to maintain consistency between the fixes.

Best Regards,
João Pedro Braz

**Comment by gurrgur** [comment]
I think it's not necessary to be so perfectionist about it at the moment. As long as they work they are fine and when (if) they break we can analyze which bytes have changed and add wildcards accordingly :)

**Comment by mikeyd85** [comment]
> Thanks for this! I'd prefer to use a pattern with wildcards to make it more robust w.r.t. possible future game updates. Though it's better to have a working patch than a non-existent perfect one ;)
> 
> Unfortunately update 1.04 has made the game crash at launch for me so I cannot test this currently.. But the path looks fine overall so I'll merge :)

I've tested this on my machine, and can confirm that it works. Pop OS 22.04 using Proton Experimental.

**Comment by joao-pedro-braz** [comment]
Hello,

That's great @mikeyd85 thanks for testing it out!
@gurrgur alright, let's keep an eye on it.

Best Regards,
João Pedro Braz

**Pull request merged**
